import { z } from 'zod';

const base = z.object({
  schemaVersion: z.literal('1'), scope: z.enum(['orientation', 'evidence', 'reproduction']), capsuleId: z.string(), canonicalUrl: z.string().url(), htmlIsCanonical: z.literal(true), permissions: z.object({ execute: z.literal(false), install: z.literal(false), publish: z.literal(false) }).strict(), synthetic: z.boolean(), investigation: z.object({ publicId: z.string(), version: z.string(), title: z.string(), question: z.string(), methodProfile: z.string(), contribution: z.string(), domains: z.array(z.string()), publishedAt: z.string(), updatedAt: z.string(), license: z.string() }).strict(), conclusion: z.object({ statement: z.string(), bounded: z.boolean(), confidence: z.string(), uncertainty: z.string(), scope: z.string() }).strict(), largestLimitation: z.string(), limitations: z.array(z.string()), review: z.string(), reproduction: z.string(),
});
const orientation = base.extend({ scope: z.literal('orientation'), whyItMatters: z.string(), summary: z.array(z.string()), claims: z.array(z.object({ label: z.string(), statement: z.string(), status: z.string(), confidence: z.string() }).strict()), sections: z.array(z.object({ label: z.string(), url: z.string().url() }).strict()) }).strict();
const source = z.union([
  z.object({ id: z.string(), access: z.literal('denied') }).strict(),
  z.object({ id: z.string(), kind: z.string(), access: z.string().refine((access) => access !== 'denied'), title: z.string().optional(), publisher: z.string().optional(), period: z.string().optional(), href: z.string().optional(), license: z.string().optional(), version: z.string().optional() }).strict(),
]);
const evidence = base.extend({ scope: z.literal('evidence'), claims: z.array(z.object({ publicId: z.string(), version: z.string(), label: z.string(), type: z.string(), statement: z.string(), scope: z.string(), status: z.string(), confidence: z.string(), uncertainty: z.string().optional(), checkedAt: z.string(), limitations: z.array(z.string()), receipts: z.array(z.object({ kind: z.string(), date: z.string() }).strict()), evidence: z.array(z.object({ id: z.string(), relation: z.string(), kind: z.string(), access: z.string(), title: z.string().optional() }).strict()), resolutionUrl: z.string().url() }).strict()), sources: z.array(source), figures: z.array(z.object({ id: z.string(), title: z.string(), classification: z.string(), reviewed: z.boolean(), uncertainty: z.string(), dataArtifact: z.object({ publicId: z.string(), version: z.string(), digest: z.string() }).strict().nullable() }).strict()) }).strict();
const reproduction = base.extend({ scope: z.literal('reproduction'), method: z.object({ profile: z.string(), fields: z.array(z.object({ key: z.string(), label: z.string(), value: z.string() }).strict()), deviations: z.array(z.string()), failures: z.array(z.string()) }).strict(), reproduce: z.object({ scopes: z.array(z.object({ scope: z.string(), state: z.string(), note: z.string() }).strict()), environment: z.array(z.object({ label: z.string(), value: z.string() }).strict()), prerequisites: z.array(z.string()), steps: z.array(z.object({ label: z.string(), command: z.string().optional() }).strict()), expected: z.string(), unavailable: z.array(z.string()), packageArtifactId: z.string().optional() }).strict(), artifacts: z.array(z.object({ publicId: z.string(), version: z.string(), digest: z.string(), id: z.string(), kind: z.string(), title: z.string(), mediaType: z.string(), bytes: z.number(), license: z.string(), href: z.string() }).strict()) }).strict();
export const capsuleSchema = z.discriminatedUnion('scope', [orientation, evidence, reproduction]);
