import { z } from 'zod';
import { METHOD_PROFILES } from './profiles.mjs';

export const exactVersion = z.string().regex(/^(?!latest$|main$|head$)[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/i, 'expected exact version');
const publicId = z.string().regex(/^[a-z][a-z0-9-]{2,79}$/, 'expected public id');
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'expected ISO date');
const digest = z.string().regex(/^sha256:[a-f0-9]{64}$/, 'expected sha256 digest');
const href = z.string().refine((value) => /^\/(?!\/)/.test(value) || (() => { try { return new URL(value).protocol === 'https:'; } catch { return false; } })(), 'expected https URL or site-relative path');
const access = z.enum(['public', 'metadata-only', 'excerpt', 'denied']);
const review = z.enum(['unreviewed', 'author-reviewed', 'automated-checks-passed', 'independently-reviewed', 'externally-peer-reviewed']);
const repro = z.enum(['not-attempted', 'local-rerun', 'external-reproduction', 'independent-replication', 'failed', 'inconclusive', 'not-applicable']);
const strict = (shape) => z.object(shape).strict();

const claim = strict({ publicId, version: exactVersion, label: z.string(), type: z.enum(['run-claim', 'source-assertion', 'inference', 'speculation', 'canonical-group']), statement: z.string(), scope: z.string(), status: z.enum(['supported-within-scope', 'mixed', 'contradicted', 'unresolved', 'unreviewed']), confidence: z.enum(['high', 'moderate', 'low', 'not-assessed']), uncertainty: z.string().optional(), checkedAt: date, domains: z.array(z.string()), limitations: z.array(z.string()), evidence: z.array(strict({ evidenceId: z.string(), relation: z.enum(['supports', 'contradicts', 'qualifies']) })), figureIds: z.array(z.string()), receipts: z.array(strict({ kind: z.enum(['source-pointer-resolved', 'author-reviewed', 'automated-check', 'independent-review']), date, note: z.string().optional() })) });
const evidence = strict({ id: z.string(), kind: z.enum(['dataset', 'analysis', 'study', 'notebook', 'source-passage', 'experiment']), access, title: z.string().optional(), origin: z.string().optional(), period: z.string().optional(), summary: z.string().optional(), review, sourceIds: z.array(z.string()), figureIds: z.array(z.string()), artifactIds: z.array(z.string()), date: date.optional() });
const source = strict({ id: z.string(), kind: z.enum(['dataset', 'journal-article', 'report', 'book', 'web', 'software']), access, title: z.string().optional(), publisher: z.string().optional(), period: z.string().optional(), summary: z.string().optional(), href: href.optional(), license: z.string().optional(), version: exactVersion.optional() });
const artifact = strict({ publicId, version: exactVersion, digest, id: z.string(), kind: z.enum(['code', 'notebook', 'dataset', 'package', 'document']), title: z.string(), summary: z.string(), mediaType: z.string(), bytes: z.number(), license: z.string(), href });
const figure = strict({ id: z.string(), number: z.number(), title: z.string(), caption: z.string(), alt: z.string(), classification: z.enum(['measured', 'simulated', 'reconstructed', 'illustrative']), reviewed: z.boolean(), uncertainty: z.string(), chart: z.union([z.null(), strict({ type: z.enum(['scatter', 'line']), x: strict({ label: z.string(), unit: z.string() }), y: strict({ label: z.string(), unit: z.string() }), series: z.array(strict({ name: z.string(), points: z.array(z.tuple([z.number(), z.number()])) })), fit: strict({ slope: z.number(), intercept: z.number(), r2: z.number(), note: z.string() }).optional() })]), dataArtifactId: z.string().optional(), codeArtifactId: z.string().optional(), claimIds: z.array(z.string()) });

export const labBundleSchema = strict({
  schemaVersion: z.literal('1'), synthetic: z.boolean(), releaseId: z.string(),
  investigation: strict({ publicId, version: exactVersion, title: z.string(), question: z.string(), dek: z.string().max(200), whyItMatters: z.string(), domains: z.array(z.string()), methodProfile: z.enum(['computational-experiment', 'evidence-review', 'mathematical-analysis', 'design-study', 'physical-investigation', 'philosophical-inquiry']), contribution: z.enum(['replication', 'reanalysis', 'synthesis', 'method-contribution', 'negative-result', 'original-finding-proposed']), contributors: z.array(strict({ name: z.string(), role: z.string() })), publishedAt: date, updatedAt: date, readMinutes: z.number().optional(), license: z.string(), featuredFigureId: z.string().optional() }),
  report: strict({ publicId, version: exactVersion, summary: z.array(z.string()), conclusion: strict({ statement: z.string(), bounded: z.boolean(), confidence: z.enum(['high', 'moderate', 'low', 'not-assessed']), uncertainty: z.string().min(1), scope: z.string() }), largestLimitation: z.string(), limitations: z.array(z.string()), review, reproduction: repro }),
  claims: z.array(claim), evidence: z.array(evidence), sources: z.array(source), figures: z.array(figure), artifacts: z.array(artifact),
  method: strict({ profile: z.enum(['computational-experiment', 'evidence-review', 'mathematical-analysis', 'design-study', 'physical-investigation', 'philosophical-inquiry']), fields: z.array(strict({ key: z.string(), label: z.string(), value: z.string() })), deviations: z.array(z.string()), failures: z.array(z.string()) }),
  reproduce: strict({ scopes: z.array(strict({ scope: z.enum(['rerun', 'reproduce', 'replicate']), state: repro, note: z.string() })), environment: z.array(strict({ label: z.string(), value: z.string() })), prerequisites: z.array(z.string()), steps: z.array(strict({ label: z.string(), command: z.string().optional() })), expected: z.string(), unavailable: z.array(z.string()), packageArtifactId: z.string().optional() }),
  timeline: z.array(strict({ date, kind: z.enum(['run', 'release', 'correction', 'review', 'withdrawal']), label: z.string(), version: exactVersion.optional(), note: z.string().optional() })),
}).superRefine((bundle, ctx) => {
  const fail = (message) => ctx.addIssue({ code: 'custom', message });
  const profile = METHOD_PROFILES[bundle.investigation.methodProfile];
  if (bundle.method.profile !== bundle.investigation.methodProfile) fail('method profile must match investigation');
  if (!profile || JSON.stringify(bundle.method.fields.map((field) => field.key)) !== JSON.stringify(profile.fields.map(([key]) => key))) fail('method fields must match profile keys in order');
  const unique = (items, key, name) => { if (new Set(items.map((item) => item[key])).size !== items.length) fail(`duplicate ${name}`); };
  unique(bundle.claims, 'label', 'claim label'); unique(bundle.claims, 'publicId', 'claim publicId'); unique(bundle.evidence, 'id', 'evidence id'); unique(bundle.sources, 'id', 'source id'); unique(bundle.figures, 'id', 'figure id'); unique(bundle.artifacts, 'id', 'artifact id'); unique(bundle.artifacts, 'publicId', 'artifact publicId');
  const evidenceIds = new Set(bundle.evidence.map((item) => item.id)), sourceIds = new Set(bundle.sources.map((item) => item.id)), figureIds = new Set(bundle.figures.map((item) => item.id)), artifactIds = new Set(bundle.artifacts.map((item) => item.id)), claimIds = new Set(bundle.claims.map((item) => item.label));
  for (const item of bundle.claims) { item.evidence.forEach((ref) => { if (!evidenceIds.has(ref.evidenceId)) fail(`unknown evidence ${ref.evidenceId}`); }); item.figureIds.forEach((id) => { if (!figureIds.has(id)) fail(`unknown figure ${id}`); }); }
  for (const item of bundle.evidence) { item.sourceIds.forEach((id) => { if (!sourceIds.has(id)) fail(`unknown source ${id}`); }); item.figureIds.forEach((id) => { if (!figureIds.has(id)) fail(`unknown figure ${id}`); }); item.artifactIds.forEach((id) => { if (!artifactIds.has(id)) fail(`unknown artifact ${id}`); }); }
  for (const item of bundle.figures) { item.claimIds.forEach((id) => { if (!claimIds.has(id)) fail(`unknown claim ${id}`); }); [item.dataArtifactId, item.codeArtifactId].filter(Boolean).forEach((id) => { if (!artifactIds.has(id)) fail(`unknown artifact ${id}`); }); if (item.chart && !item.dataArtifactId) fail('chart requires dataArtifactId'); }
  if (bundle.reproduce.packageArtifactId && !artifactIds.has(bundle.reproduce.packageArtifactId)) fail(`unknown artifact ${bundle.reproduce.packageArtifactId}`);
  if (bundle.investigation.featuredFigureId && !figureIds.has(bundle.investigation.featuredFigureId)) fail(`unknown figure ${bundle.investigation.featuredFigureId}`);
  for (const item of [...bundle.evidence, ...bundle.sources]) if (item.access === 'denied' && ['title', 'origin', 'period', 'summary', 'href', 'publisher', 'license', 'version'].some((key) => key in item)) fail('denied item must not carry metadata');
  if (bundle.timeline.some((event) => event.kind === 'release')) fail('timeline may not contain release events');
});
