import test from 'node:test';
import assert from 'node:assert/strict';
import { digestProjection } from '../../src/lib/projection/gate.mjs';
import { loadLabCatalog } from '../../src/lib/labs/load.mjs';

const version = 'v1'; const hash = 'sha256:' + 'a'.repeat(64);
const bundle = () => ({ schemaVersion: '1', synthetic: true, releaseId: 'release-one', investigation: { publicId: 'lab-one', version, title: 'Synthetic Lab', question: 'Question?', dek: 'Synthetic dek', whyItMatters: 'Synthetic reason', domains: ['test'], methodProfile: 'evidence-review', contribution: 'synthesis', contributors: [{ name: 'Synthetic Author', role: 'author' }], publishedAt: '2026-01-01', updatedAt: '2026-01-02', license: 'CC0', featuredFigureId: 'F1' }, report: { publicId: 'report-one', version, summary: ['Synthetic summary'], conclusion: { statement: 'Synthetic result', bounded: true, confidence: 'low', uncertainty: 'Synthetic uncertainty', scope: 'Synthetic scope' }, largestLimitation: 'Synthetic limit', limitations: [], review: 'unreviewed', reproduction: 'not-attempted' }, claims: [{ publicId: 'claim-one', version, label: 'C1', type: 'run-claim', statement: 'Synthetic claim', scope: 'test', status: 'unreviewed', confidence: 'not-assessed', checkedAt: '2026-01-01', domains: [], limitations: [], evidence: [{ evidenceId: 'E1', relation: 'supports' }], figureIds: ['F1'], receipts: [] }], evidence: [{ id: 'E1', kind: 'analysis', access: 'public', title: 'Synthetic evidence', review: 'unreviewed', sourceIds: ['S1'], figureIds: ['F1'], artifactIds: ['A1'] }], sources: [{ id: 'S1', kind: 'report', access: 'public', title: 'Synthetic source' }], figures: [{ id: 'F1', number: 1, title: 'Synthetic figure', caption: 'Synthetic', alt: 'Synthetic', classification: 'measured', reviewed: false, uncertainty: 'Synthetic', chart: { type: 'line', x: { label: 'x', unit: 'x' }, y: { label: 'y', unit: 'y' }, series: [] }, dataArtifactId: 'A1', claimIds: ['C1'] }], artifacts: [{ publicId: 'artifact-one', version, digest: hash, id: 'A1', kind: 'dataset', title: 'Synthetic artifact', summary: 'Synthetic', mediaType: 'text/plain', bytes: 1, license: 'CC0', href: '/download' }], method: { profile: 'evidence-review', fields: ['cutoff', 'databases', 'queries', 'inclusion', 'editions', 'extraction', 'conflicts'].map((key) => ({ key, label: key, value: 'Synthetic' })), deviations: [], failures: [] }, reproduce: { scopes: [], environment: [], prerequisites: [], steps: [], expected: 'Synthetic', unavailable: [] }, timeline: [{ date: '2026-01-01', kind: 'run', label: 'Started' }] });
function source(mutator = () => {}) { const b = bundle(); mutator(b); const specs = [['lab-investigation', b.investigation.publicId, b.investigation.version], ['lab-report', b.report.publicId, b.report.version], ['rf-claim', b.claims[0].publicId, b.claims[0].version], ['lab-artifact', b.artifacts[0].publicId, b.artifacts[0].version]]; const records = specs.map(([kind, publicId, itemVersion]) => { const record = { publicId, kind, version: itemVersion, lifecycle: 'approved', sourceRefs: ['rf:synthetic:record@v1'], dependencies: [], destinations: [] }; return { ...record, digest: digestProjection({ ...record, digest: undefined }) }; }); return { fixture: true, bundle: b, records, manifest: { schemaVersion: '1', releaseId: b.releaseId, records: records.map(({ publicId, kind, version: itemVersion, digest }) => ({ publicId, kind, version: itemVersion, digest })) }, receipts: records.map((record) => ({ schemaVersion: '1', action: 'release', publicId: record.publicId, kind: record.kind, version: record.version, digest: record.digest, approver: 'human:nick', approvedAt: '2026-01-03T00:00:00.000Z', sourceRefs: record.sourceRefs })) }; }
test('loads valid synthetic source and appends release', async () => { const catalog = await loadLabCatalog({ sources: [source()] }); assert.equal(catalog.labs.length, 1); assert.equal(catalog.labs[0].counts.artifacts, 1); assert.deepEqual(catalog.labs[0].timeline.map(({ kind }) => kind), ['run', 'release']); });
test('rejects schema violations and version aliases', async () => { const unknown = source((b) => { b.unexpected = true; }); const latest = source((b) => { b.report.version = 'latest'; }); const head = source((b) => { b.report.version = 'HEAD'; }); const result = await loadLabCatalog({ sources: [unknown, latest, head] }); assert.equal(result.rejected.length, 3); assert.ok(result.rejected[0].errors.some((error) => error.startsWith('schema:'))); });
test('rejects missing required record approvals', async () => { for (const kind of ['lab-investigation', 'lab-report', 'rf-claim']) { const input = source(); const record = input.records.find((item) => item.kind === kind); input.records = input.records.filter((item) => item !== record); input.manifest.records = input.manifest.records.filter((item) => item.publicId !== record.publicId); input.receipts = input.receipts.filter((item) => item.publicId !== record.publicId); const result = await loadLabCatalog({ sources: [input] }); assert.equal(result.labs.length, 0); assert.equal(result.rejected.length, 1); } });
test('withholds version-mismatched artifacts while preserving the Lab', async () => { const input = source(); input.bundle.artifacts[0].version = 'v2'; const result = await loadLabCatalog({ sources: [input] }); assert.equal(result.labs[0].artifacts.length, 0); assert.equal(result.labs[0].figureData.F1, null); });
test('rejects denied evidence metadata', async () => { const input = source((b) => { b.evidence[0].access = 'denied'; }); const result = await loadLabCatalog({ sources: [input] }); assert.ok(result.rejected[0].errors.some((error) => error.startsWith('schema:denied item'))); });
test('rejects an unapproved release and synthetic mismatch', async () => { const unapproved = source(); unapproved.receipts = unapproved.receipts.filter((item) => item.kind !== 'lab-report'); const mismatch = source(); mismatch.fixture = false; const result = await loadLabCatalog({ sources: [unapproved, mismatch] }); assert.equal(result.rejected.length, 2); assert.ok(result.rejected[1].errors.includes('synthetic-mismatch')); });
test('withholds unrecorded artifacts while keeping lab', async () => { const input = source(); input.records.pop(); input.manifest.records.pop(); input.receipts.pop(); const result = await loadLabCatalog({ sources: [input] }); assert.equal(result.labs[0].artifacts.length, 0); assert.equal(result.labs[0].figureData.F1, null); });
test('makes a tombstone for withdrawal', async () => { const input = source(); input.receipts.push({ ...input.receipts[0], action: 'withdraw', approver: 'human:nick', reason: 'Synthetic withdrawal' }); const result = await loadLabCatalog({ sources: [input] }); assert.equal(result.tombstones.length, 1); assert.equal(result.labs.length, 0); });
test('does not load fixtures when absent', async () => { const result = await loadLabCatalog({ includeFixtures: false }); assert.deepEqual(result.labs, []); });
